### ISSUE TITLE
rkscript raises KeyError: 'config_messages_rel_path'

### ISSUE THREAD

**Issue by yggdr** [korniichuk/rk#13]
Starting a remote kernel (as per you example) or even running `rkscript` manually always results in this error:
```
Traceback (most recent call last):
  File "/root/.local/bin/rkscript", line 110, in <module>
    create_messages()
  File "/root/.local/bin/rkscript", line 103, in create_messages
    config_messages_rel_path = config["config_messages_rel_path"]
  File "/root/.local/lib/python2.7/site-packages/configobj.py", line 554, in __getitem__
    val = dict.__getitem__(self, key)
KeyError: 'config_messages_rel_path'
```

Installed rk via pip-2.7 in a FreeBSD 10.3 jail

**Comment by russellsmithies** [comment]
I have the same issue,has anyone found the solution yet? It makes rk unusable :-(
```
[I 10:51:15.443 NotebookApp] Kernel started: 7a003dd5-47a7-468f-a33e-490e7f1e37c5
Traceback (most recent call last):
  File "/usr/bin/rkscript", line 110, in <module>
    create_messages()
  File "/usr/bin/rkscript", line 103, in create_messages
    config_messages_rel_path = config["config_messages_rel_path"]
  File "/usr/lib/python2.7/site-packages/configobj.py", line 567, in __getitem__
    val = dict.__getitem__(self, key)
KeyError: 'config_messages_rel_path'
[I 10:51:18.438 NotebookApp] KernelRestarter: restarting kernel (1/5), new random ports
Traceback (most recent call last):
  File "/usr/bin/rkscript", line 110, in <module>
    create_messages()
  File "/usr/bin/rkscript", line 103, in create_messages
    config_messages_rel_path = config["config_messages_rel_path"]
  File "/usr/lib/python2.7/site-packages/configobj.py", line 567, in __getitem__
    val = dict.__getitem__(self, key)
KeyError: 'config_messages_rel_path'
