### ISSUE TITLE
Pip install error

### ISSUE THREAD

**Issue by abalter** [korniichuk/rk#15]
```
alter@BICB260:~/rk$ pip install rk
Collecting rk
  Using cached rk-0.3b1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/qm/b_1n3bn15wb373zvkvd1vcp4yjd86m/T/pip-build-ki70csci/rk/setup.py", line 39, in <module>
        long_description = open(join(dirname(__file__), "README.rst")).read(),
      File "/Users/balter/miniconda3/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 2208: ordinal not in range(128)

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/qm/b_1n3bn15wb373zvkvd1vcp4yjd86m/T/pip-build-ki70csci/rk/
```

**Comment by abalter** [comment]
Likewise for development version:

```
balter@BICB260:~$ git clone git://github.com/korniichuk/rk.git
Cloning into 'rk'...
remote: Counting objects: 342, done.
remote: Total 342 (delta 0), reused 0 (delta 0), pack-reused 342
Receiving objects: 100% (342/342), 217.93 KiB | 0 bytes/s, done.
Resolving deltas: 100% (191/191), done.
balter@BICB260:~$ cd rk
balter@BICB260:~/rk$ pip install .
Processing /Users/balter/rk
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/qm/b_1n3bn15wb373zvkvd1vcp4yjd86m/T/pip-tnxto887-build/setup.py", line 39, in <module>
        long_description = open(join(dirname(__file__), "README.rst")).read(),
      File "/Users/balter/miniconda3/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 2208: ordinal not in range(128)

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/qm/b_1n3bn15wb373zvkvd1vcp4yjd86m/T/pip-tnxto887-build/
```
